"""Contract for scripts/build_works.py: build fixture works in a temporary site copy.

    python3 tests/works_contract.py
"""
import json
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
import build_works  # noqa: E402


def make_video(path, seconds=2, size="720x1280"):
    subprocess.run(
        ["ffmpeg", "-v", "error", "-y", "-f", "lavfi", "-i", f"testsrc=size={size}:rate=24:duration={seconds}",
         "-f", "lavfi", "-i", f"sine=frequency=440:duration={seconds}", "-shortest",
         "-c:v", "libx264", "-pix_fmt", "yuv420p", "-c:a", "aac", str(path)],
        check=True,
    )


NOTE = """标题: 测试作品 {n}
模型: {model}
标签: 剪映
日期: 2026-09-{day:02d}
视频: clip.mp4
归属: 个人作品
简介: 合同测试用的合成视频。
原帖: https://x.com/zzchen275198/status/1

## 工具
- 即创「视频SD 2.0」

## 提示词
```
一个 <script>alert(1)</script> 测试提示词
```

## 步骤
1. 先写分镜。
2. 再生成。

## 踩过的坑
- 字幕会被模型改写。
"""


class BuildWorksContract(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.tmp = Path(tempfile.mkdtemp(prefix="works-contract-"))
        for rel in ["index.html", "works/index.html", "sitemap.xml", "works/nv-guse/index.html",
                    "works/sucai-fangfa/index.html", "content/works/nv-guse/note.md",
                    "content/works/sucai-fangfa/note.md", "assets/materials/proof-video-timing-13s.png"]:
            dest = cls.tmp / rel
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(ROOT / rel, dest)
        for n in range(1, 5):
            model = "即梦" if n <= 3 else "Google Flow / Veo"
            folder = cls.tmp / "content" / "works" / f"fixture-{n}"
            folder.mkdir(parents=True)
            make_video(folder / "clip.mp4", size="1440x2560" if n == 1 else "720x1280")
            (folder / "note.md").write_text(NOTE.format(n=n, model=model, day=10 + n), encoding="utf-8")
        cls.works = build_works.build(cls.tmp)

    @classmethod
    def tearDownClass(cls):
        shutil.rmtree(cls.tmp)

    def read(self, rel):
        return (self.tmp / rel).read_text(encoding="utf-8")

    def test_media_is_web_ready_1080p(self):
        out = self.tmp / "media/works/fixture-1"
        info = json.loads(subprocess.run(
            ["ffprobe", "-v", "quiet", "-print_format", "json", "-show_streams", "-show_format", str(out / "video.mp4")],
            capture_output=True, text=True, check=True).stdout)
        video = next(s for s in info["streams"] if s["codec_type"] == "video")
        self.assertEqual((video["codec_name"], video["width"], video["height"]), ("h264", 1080, 1920))
        with open(out / "video.mp4", "rb") as handle:
            head = handle.read(4096)
        moov, mdat = head.find(b"moov"), head.find(b"mdat")
        self.assertNotEqual(moov, -1, "faststart puts the moov atom at the start of the file")
        self.assertTrue(mdat == -1 or moov < mdat, "moov comes before mdat")
        self.assertTrue((out / "poster.jpg").is_file() and (out / "poster-sm.jpg").is_file())
        small = json.loads(subprocess.run(["ffprobe", "-v", "quiet", "-print_format", "json", "-show_streams",
                                           str(self.tmp / "media/works/fixture-2/video.mp4")],
                                          capture_output=True, text=True, check=True).stdout)["streams"][0]
        self.assertEqual((small["width"], small["height"]), (720, 1280), "never upscales")

    def test_detail_page(self):
        page = self.read("works/fixture-1/index.html")
        self.assertIn("<!-- generated by build_works.py -->", page)
        self.assertIn('preload="none"', page)
        self.assertIn('poster="/media/works/fixture-1/poster.jpg"', page)
        self.assertIn('<link rel="canonical" href="https://chenzhihong.online/works/fixture-1/">', page)
        self.assertIn("&lt;script&gt;alert(1)&lt;/script&gt;", page, "prompts are escaped")
        self.assertNotIn("<script>alert(1)</script>", page)
        for section in build_works.SECTIONS:
            self.assertIn(f"<h2>{section}</h2>", page)
        self.assertIn("在X看原帖", page)
        self.assertIn("个人作品", page)
        self.assertEqual(page.count('aria-current="page"'), 1)

    def test_two_columns_with_model_tags(self):
        wall = self.read("works/index.html")
        self.assertIn('id="ai"', wall, "every AI work sits in one AI 视频 column")
        self.assertIn('id="cases"', wall)
        self.assertLess(wall.index('id="ai"'), wall.index('id="cases"'))
        self.assertEqual(wall.count('class="work-card"'), 4, "all four fixtures, whatever their model")
        self.assertIn('<li>Google Flow / Veo</li>', self.read("works/fixture-4/index.html"), "model shown as a tag")

    def test_home_and_sitemap_blocks(self):
        home = self.read("index.html")
        self.assertIn('class="hero-reel has-sides"', home)
        self.assertIn('data-play', home, "featured video only loads on click")
        self.assertIn('<video controls playsinline preload="none"', home)
        self.assertEqual(home.count("<!-- works:latest:start -->"), 1)
        self.assertIn("/works/fixture-4/", home)
        sitemap = self.read("sitemap.xml")
        self.assertIn("<loc>https://chenzhihong.online/works/fixture-1/</loc>", sitemap)
        self.assertNotIn("/works/nv-guse/</loc><lastmod>2026-02", sitemap)

    def test_rebuild_is_idempotent_and_removes_deleted_works(self):
        before = self.read("works/index.html")
        build_works.build(self.tmp)
        self.assertEqual(before, self.read("works/index.html"))
        extra = self.tmp / "content/works/fixture-extra"
        extra.mkdir()
        make_video(extra / "clip.mp4", seconds=1)
        (extra / "note.md").write_text(NOTE.format(n=9, model="即梦", day=1), encoding="utf-8")
        build_works.build(self.tmp)
        self.assertTrue((self.tmp / "works/fixture-extra/index.html").exists())
        shutil.rmtree(extra)
        build_works.build(self.tmp)
        self.assertFalse((self.tmp / "works/fixture-extra").exists(), "pages of deleted works are removed")
        self.assertTrue((self.tmp / "works/nv-guse/index.html").exists(), "hand-written case pages stay")
        self.assertEqual(before, self.read("works/index.html"))

    def test_rejects_bad_notes(self):
        bad = self.tmp / "content/works/bad-note"
        bad.mkdir()
        make_video(bad / "clip.mp4", seconds=1)
        (bad / "note.md").write_text(NOTE.format(n=9, model="即梦", day=1).replace("归属: 个人作品", "归属: 不确定"),
                                     encoding="utf-8")
        with self.assertRaises(build_works.NoteError):
            build_works.load_work(bad)
        shutil.rmtree(bad)


if __name__ == "__main__":
    unittest.main(verbosity=2)
